name: Visitor Counter

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  collect-visitor-data:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Run the visitor counter script
      - name: Run visitor counter
        run: python main.py

      # Configure Git
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # Commit and push changes if any
      - name: Commit and push
        run: |
          git add -A
          git commit -m "Update visitor data: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push || echo "No changes to push"
