name: Visitor Counter

on:
  schedule:
    # Run a bit before each 15-minute mark to ensure we catch the interval
    - cron: "2,17,32,47 * * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  collect-visitor-data:
    runs-on: ubuntu-latest

    # Add permission to allow committing and pushing
    permissions:
      contents: write

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Run the visitor counter script
      - name: Run visitor counter
        run: |
          python main.py
          echo "Contents of data directory:"
          ls -la data/ || echo "Data directory not found"

      # Commit and push changes using a dedicated action
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update visitor data [skip ci]"
          add: "data/"
          default_author: github_actions
